---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Suse.yml
  when: ansible_os_family == 'Suse'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: Solaris.yml
  when: ansible_os_family == 'Solaris'

- name: Download Eclipse
  get_url: url={{ eclipse_platform_url_452_64 }}
           dest=/opt/eclipse-platform-{{ eclipse_platform_release }}-{{ ansible_architecture}}.tar.gz
           checksum=sha1:669cac5ae2424514634fbd36394f9b41a443b9b6
  when: (eclipse_platform_release == "4.5.2") and (ansible_architecture == "x86_64")

- name: Extract Eclipse 
  unarchive: src=/opt/eclipse-platform-{{ eclipse_platform_release }}-{{ ansible_architecture}}.tar.gz
             dest=/opt
             creates=/opt/eclipse/eclipse

- name: Create /usr/local/bin/eclipse symlink
  file: src=/opt/eclipse/eclipse
        dest=/usr/local/bin/eclipse
        state=link

